from enum import StrEnum


class NodeType(StrEnum):
    AGENT = "agent"
    ASSET = "asset"
    BUSINESS_SERVICE = "business_service"
    CONNECTOR = "connector"
    CONTROL = "control"
    DATA_FLOW = "data_flow"
    DATA_SET = "data_set"
    DEVICE = "device"
    EVIDENCE = "evidence"
    FINDING = "finding"
    IDENTITY = "identity"
    INCIDENT = "incident"
    MODEL = "model"
    OBLIGATION = "obligation"
    POLICY = "policy"
    PROCESSING_ACTIVITY = "processing_activity"
    PROMPT = "prompt"
    RESPONSE = "response"
    RISK = "risk"
    SCENARIO = "scenario"
    SESSION = "session"
    TENANT = "tenant"
    THREAT_ACTOR = "threat_actor"
    ATTACK_TECHNIQUE = "attack_technique"
    TOOL = "tool"
    VULNERABILITY = "vulnerability"
    WORKFLOW = "workflow"


class EdgeType(StrEnum):
    ACCESSES = "accesses"
    AFFECTS = "affects"
    CLASSIFIES = "classifies"
    DELEGATES_TO = "delegates_to"
    DEPENDS_ON = "depends_on"
    DERIVED_FROM = "derived_from"
    EVIDENCES = "evidences"
    EXPOSED_TO = "exposed_to"
    GOVERNED_BY = "governed_by"
    IMPERSONATES = "impersonates"
    INVOKES = "invokes"
    LINKED_TO = "linked_to"
    MITIGATES = "mitigates"
    OBSERVED = "observed"
    OWNS = "owns"
    PROCESSES = "processes"
    PROTECTED_BY = "protected_by"
    QUANTIFIES = "quantifies"
    REQUIRES = "requires"
    RUNS_ON = "runs_on"
    STORES = "stores"
    TRANSFERS_TO = "transfers_to"
    USES = "uses"
    VIOLATES = "violates"
